version: '3'
services:
  sslproxy:
    image: zsoerenm/magento2-sslproxy:2.2.6
    depends_on:
      - varnish
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certs:/etc/nginx/ssl
    environment:
      - BACKEND_HOST=varnish
      - SERVER_NAME=localhost

  varnish:
    image: zsoerenm/magento2-varnish:2.2.6
    depends_on:
      - web

  redis:
    image: redis:alpine

  web:
    image: zsoerenm/magento2-nginx:2.2.6
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html:ro
    environment:
      - BACKEND_HOST=php
      - SERVER_NAME=web

  php:
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    image: shofiul/magento:2.3.0
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    environment:
      - DEFAULT_CACHE_REDIS_SERVER=redis
      - DEFAULT_CACHE_REDIS_DATABASE=1
      - PAGE_CACHE_REDIS_SERVER=redis
      - PAGE_CACHE_REDIS_DATABASE=2
      - SESSION_REDIS_SERVER=redis
      - SESSION_REDIS_DATABASE=3


  db:
    image: mariadb:10.2
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: 'mysqladmin ping --silent'
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  cron:
    image: shofiul/magento:2.3.0
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html:z
    entrypoint: "su magento -s /bin/sh -c 'trap exit TERM; while :; do bin/magento cron:run; sleep 1m & wait $${!}; done;'"

volumes:
  dbdata:
  appdata:
  mediadata:
  configdata:
  webconfig:
