version: '3'
services:

  sslproxy:
    image: magento2-sslproxy
    depends_on:
      - varnish
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certs/localhost+2-key.pem:/etc/nginx/ssl/nginx.key
      - ./certs/localhost+2.pem:/etc/nginx/ssl/nginx.crt
    environment:
      - BACKEND_HOST=varnish
      - SERVER_NAME=localhost

  varnish:
    image: magento2-varnish
    depends_on:
      - web

  redis:
    image: redis:alpine

  web:
    image: magento2-nginx-prod
    depends_on:
      - php
    volumes:
      - mediadata:/var/www/html/pub/media:ro
    environment:
      - BACKEND_HOST=php
      - SERVER_NAME=web

  php:
    image: magento2-php-prod
    depends_on:
      - db
    volumes:
      - mediadata:/var/www/html/pub/media
      - configdata:/var/www/html/app/etc
    environment:
      - DEFAULT_CACHE_REDIS_SERVER=redis
      - DEFAULT_CACHE_REDIS_DATABASE=1
      - PAGE_CACHE_REDIS_SERVER=redis
      - PAGE_CACHE_REDIS_DATABASE=2
      - SESSION_REDIS_SERVER=redis
      - SESSION_REDIS_DATABASE=3

  db:
    image: mariadb:10.2
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: 'mysqladmin ping --silent'
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  cron:
    image: magento2-php-prod
    depends_on:
      - db
    volumes:
      - mediadata:/var/www/html/pub/media
      - configdata:/var/www/html/app/etc
    entrypoint: "su magento -s /bin/sh -c 'trap exit TERM; while :; do bin/magento cron:run; sleep 1m & wait $${!}; done;'"

volumes:
  dbdata:
  mediadata:
  configdata:
